.TH KEYD 8
.SH NAME
onak-keydctl \- control an onak keyd instance
.SH SYNOPSIS
.PP
.B onak-keydctl
[
.B options
]
.B command
.SH DESCRIPTION
.PP
keydctl is a command line client for interacting with a backend onak-keyd
daemon. It's intended to perform functions that are specifically related
to onak-keyd rather than being generic keyserver functions. See
.BR onak(1)
for details about how to perform key related operations.
.SS "Options"
.TP
\fB\-c \fIFILE\fR\fR
Use \fIFILE\fR as the config file instead of the default.
.TP
\fB\-h\fR
Display help text.
.SS "Commands"
.TP
.B check
Query if onak-keyd is running and accepting commands. Returns 0 if it is, 1
otherwise. Outputs nothing to stdout/stderr.
.TP
.B quit
Request that onak-keyd exits cleanly
.TP
.B status
Display the status of a running onak-keyd. Currently the protocol version in use,
when onak-keyd was started, the number of client connections seen and a breakdown
of the commands seen.
.SH FILES
.br
.nf
.\" set tabstop to longest possible filename, plus a wee bit
.ta \w'/usr/lib/perl/getopts.pl   'u
\fI/etc/onak.ini\fR	default configuration file
.SH NOTES
This man page could probably do with some more details.
.SH "SEE ALSO"
.BR onak (1)
.BR onak-keyd (8)
.SH AUTHOR
onak was written by Jonathan McDowell <noodles@earth.li>. It can be found at
https://www.earth.li/projectpurple/progs/onak.html
