language: c
dist: bionic
compiler:
  - clang
  - gcc
git:
  depth: false
addons:
  apt:
    packages:
      - cmake
      - libdb-dev
      - libcurl4-gnutls-dev
      - libpq-dev
      - libsystemd-dev
      - nettle-dev
before_script:
  - mkdir travis-build
  - cd travis-build
  - cmake ..
script: make && make test
