#! /bin/sh

set -e

if [ "$1" = "purge" ]; then
    if dpkg-statoverride --list /usr/lib/cgi-bin/pks/\* >/dev/null; then
        for i in $(dpkg-statoverride --list /usr/lib/cgi-bin/pks/\* | cut -d " " -f 4); do
            dpkg-statoverride --remove $i
	done
    fi

    rm -f /var/log/onak.log /var/log/onak.log.1 /var/log/onak.log.*.gz

    # Clean up any key databases, if they exist
    if [ -d /var/lib/onak -a ! -z "$(ls -A /var/lib/onak)" ]; then
        rm -f /var/lib/onak/*
    fi
fi

#DEBHELPER#
