#! /bin/sh

set -e

if [ "$1" = "purge" ]; then
    if dpkg-statoverride --list /usr/lib/cgi-bin/pks/\* >/dev/null; then
        for i in $(dpkg-statoverride --list /usr/lib/cgi-bin/pks/\* | cut -d " " -f 4); do
            dpkg-statoverride --remove $i
	done
    fi

    rm -f /var/log/onak.log{,.1,.*.gz}
fi
